kalite/securesync/urls.py
from django.http import HttpResponse, HttpResponseRedirect
from django.conf.urls.defaults import patterns, include, url
import views

urlpatterns = patterns('securesync.api_views',
    url(r'^api/register$', 'register_device', {}, 'register_device'),
    url(r'^api/test$', 'test_connection', {}, 'test_connection'),
    url(r'^api/session/create$', 'create_session', {}, 'create_session'),
    url(r'^api/session/destroy$', 'destroy_session', {}, 'destroy_session'),
    url(r'^api/device/counters$', 'device_counters', {}, 'device_counters'),
    url(r'^api/device/download$', 'device_download', {}, 'device_download'),
    url(r'^api/models/download$', 'download_models', {}, 'download_models'),
    url(r'^api/models/upload$', 'upload_models', {}, 'upload_models'),
    url(r'^api/status$', 'status', {}, 'status'),
)

urlpatterns += patterns('securesync.views',
    url(r'^register/$', 'register_public_key', {}, 'register_public_key'),
    url(r'^addteacher/$', 'add_facility_teacher', {}, 'add_facility_teacher'),
    url(r'^addstudent/$', 'add_facility_student', {}, 'add_facility_student'),
    url(r'^facility/$', 'facility_admin', {}, 'facility_admin'),
    url(r'^facility/new/$', 'facility_edit', {"id": "new"}, 'add_facility'),
    url(r'^facility/(?P<id>\w+)/$', 'facility_edit', {}, 'facility_edit'),
    url(r'^addgroup/$', 'add_group', {}, 'add_group'),
    url(r'^cryptologin/$', 'crypto_login', {}, 'crypto_login'),
    url(r'^login/$', 'login', {}, 'login'),
    url(r'^logout/$', 'logout', {}, 'logout'),
)

kalite/urls.py
from django.http import HttpResponseRedirect
from django.conf.urls.defaults import patterns, include, url
import securesync.urls
from kalite import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^images/(.+)$', lambda request, path: HttpResponseRedirect('/static/images/' + path)),
    url(r'^securesync/', include(securesync.urls)),
)

urlpatterns += patterns('',
    url(r'^' + settings.CONTENT_URL[1:] + '(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.CONTENT_ROOT,
    }),
    url(r'^' + settings.MEDIA_URL[1:] + '(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
)

# Javascript translations
urlpatterns += patterns('',
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': ('ka-lite.locale')}, 'i18n_javascript_catalog'),
)

if settings.CENTRAL_SERVER:
    
    from central.feeds import RssSiteNewsFeed, AtomSiteNewsFeed

    urlpatterns += patterns('central.views',
        url(r'^$', 'homepage', {}, 'homepage'), 
        url(r'^delete_admin/(?P<org_id>\w+)/(?P<user_id>\w+)/$', 'delete_admin', {}, 'delete_admin'), 
        url(r'^delete_invite/(?P<org_id>\w+)/(?P<invite_id>\w+)/$', 'delete_invite', {}, 'delete_invite'), 
        url(r'^accounts/', include('registration.urls')),
        url(r'^organization/(?P<id>\w+)/$', 'organization_form', {}, 'organization_form'),
        url(r'^organization/(?P<org_id>\w+)/zone/(?P<id>\w+)/$', 'zone_form', {}, 'zone_form'),
        url(r'^organization/invite_action/(?P<invite_id>\w+)/$', 'org_invite_action', {}, 'org_invite_action'),
        url(r'^organization/(?P<org_id>\w+)/zone/(?P<zone_id>\w+)/facility/$', 'central_facility_admin', {}, 'central_facility_admin'),
        url(r'^organization/(?P<org_id>\w+)/zone/(?P<zone_id>\w+)/facility/new/$', 'central_facility_edit', {"id": "new"}, 'central_facility_add'),
        url(r'^organization/(?P<org_id>\w+)/zone/(?P<zone_id>\w+)/facility/(?P<id>\w+)/$', 'central_facility_edit', {}, 'central_facility_edit'),
        url(r'^cryptologin/$', 'crypto_login', {}, 'crypto_login'), 
        url(r'^getstarted/$','get_started', {}, 'get_started'),
        url(r'^glossary/$', 'glossary', {}, 'glossary'),
        url(r'^addsubscription/$', 'add_subscription', {}, 'add_subscription'),
        url(r'^feeds/rss/$', RssSiteNewsFeed(), {}, 'rss_feed'),
        url(r'^feeds/atom/$', AtomSiteNewsFeed(), {}, 'atom_feed'),
        url(r'^faq/', include('faq.urls')),
    )
    
    handler404 = 'main.views.central_404_handler'
    handler500 = 'main.views.central_500_handler'

else:
    
    urlpatterns += patterns('main.views',
        url(r'^exercisedashboard/$', 'exercise_dashboard', {}, 'exercise_dashboard'),
        url(r'^coachreports/$', 'coach_reports', {}, 'coach_reports'),
        url(r'^$', 'homepage', {}, 'homepage'),
        url(r'^update/$', 'update', {}, 'update'),
        url(r'^userlist/$', 'user_list', {}, 'user_list'),
        url(r'^api/', include('main.api_urls')),
        
        # the following pattern is a catch-all, so keep it last:
        url(r'^(?P<splat>.+)/$', 'splat_handler', {}, 'splat_handler'),
    )
    
    handler404 = 'main.views.distributed_404_handler'
    handler500 = 'main.views.distributed_500_handler'

kalite/config/models.py
from django.db import models

class Settings(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    value = models.TextField(blank=True)
    datatype = models.CharField(max_length=10, default="str")
    
    @staticmethod
    def set(name, value):
        setting = Settings(name=name, value=str(value), datatype=value.__class__.__name__)
        setting.save()
        
    @staticmethod
    def get(name, default=""):
        try:
            setting = Settings.objects.get(name=name)
            if setting.datatype == "int":
                return int(setting.value)
            if setting.datatype == "float":
                return float(setting.value)
            if setting.datatype == "bool":
                return bool(setting.value)
            return setting.value
        except Settings.DoesNotExist:
            return default
        
    class Meta:
        verbose_name = "Settings"
        verbose_name_plural = "Settings"

kalite/securesync/models.py
from annoying.functions import get_object_or_None
from django.contrib.auth.models import User, check_password
from django.core import serializers
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import models, transaction
from django.db.models import Q
from django.utils.text import compress_string
from config.models import Settings
import crypto
import datetime
import uuid
import zlib
import settings
from pbkdf2 import crypt
from django.utils.translation import ugettext_lazy as _


_unhashable_fields = ["signature", "signed_by"]
_always_hash_fields = ["signed_version", "id"]

json_serializer = serializers.get_serializer("json")()

# ROOT_UUID_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, settings.CENTRAL_SERVER_HOST)
ROOT_UUID_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "https://kalite.adhocsync.com/")


class SyncSession(models.Model):
    client_nonce = models.CharField(max_length=32, primary_key=True)
    client_device = models.ForeignKey("Device", related_name="client_sessions")
    server_nonce = models.CharField(max_length=32, blank=True)
    server_device = models.ForeignKey("Device", blank=True, null=True, related_name="server_sessions")
    verified = models.BooleanField(default=False)
    ip = models.CharField(max_length=50, blank=True)
    client_version = models.CharField(max_length=100, blank=True)
    client_os = models.CharField(max_length=200, blank=True)
    timestamp = models.DateTimeField(auto_now=True)
    models_uploaded = models.IntegerField(default=0)
    models_downloaded = models.IntegerField(default=0)
    closed = models.BooleanField(default=False)
    
    def _hashable_representation(self):
        return "%s:%s:%s:%s" % (
            self.client_nonce, self.client_device.pk,
            self.server_nonce, self.server_device.pk,
        )
        
    def _verify_signature(self, device, signature):
        return device.get_key().verify(self._hashable_representation(), signature)

    def verify_client_signature(self, signature):
        return self._verify_signature(self.client_device, signature)

    def verify_server_signature(self, signature):
        return self._verify_signature(self.server_device, signature)

    def sign(self):
        return Device.get_own_device().get_key().sign(self._hashable_representation())
        
    def __unicode__(self):
        return "%s... -> %s..." % (self.client_device.pk[0:5],
            (self.server_device and self.server_device.pk[0:5] or "?????"))


class RegisteredDevicePublicKey(models.Model):
    public_key = models.CharField(max_length=500, help_text="(this field should be filled in automatically; don't change it)")
    zone = models.ForeignKey("Zone")

    def __unicode__(self):
        return "%s... (Zone: %s)" % (self.public_key[0:5], self.zone)


class DeviceMetadata(models.Model):
    device = models.OneToOneField("Device", blank=True, null=True)
    is_trusted = models.BooleanField(default=False)
    is_own_device = models.BooleanField(default=False)
    counter_position = models.IntegerField(default=0)

    class Meta:    
        verbose_name_plural = "Device metadata"

    def __unicode__(self):
        return "(Device: %s)" % (self.device)


class SyncedModelManager(models.Manager):
    
    def by_zone(self, zone):
        # get model instances that were signed by devices in the zone,
        # or signed by a trusted authority that said they were for the zone
        return self.filter(Q(signed_by__devicezone__zone=zone) |
            Q(signed_by__devicemetadata__is_trusted=True, zone_fallback=zone))

class SyncedModel(models.Model):
    id = models.CharField(primary_key=True, max_length=32, editable=False)
    counter = models.IntegerField(default=0)
    signature = models.CharField(max_length=360, blank=True, editable=False)
    signed_version = models.IntegerField(default=1, editable=False)
    signed_by = models.ForeignKey("Device", blank=True, null=True, related_name="+")
    zone_fallback = models.ForeignKey("Zone", blank=True, null=True, related_name="+")
    deleted = models.BooleanField(default=False)

    objects = SyncedModelManager()

    def sign(self, device=None):
        if not self.id:
            self.id = self.get_uuid()
        self.signed_by = device or Device.get_own_device()
        self.signature = self.signed_by.get_key().sign(self._hashable_representation())

    def verify(self):
        # if nobody signed it, verification fails
        if not self.signed_by_id:
            return False
        # if it's not a trusted device...
        if not self.signed_by.get_metadata().is_trusted:
            # but it's a model class that requires trusted signatures, verification fails
            if self.requires_trusted_signature:
                return False
            if settings.CENTRAL_SERVER:
                # if it's not in a zone at all (or its DeviceZone was revoked), verification fails
                if not self.signed_by.get_zone():
                    return False
            else:
                # or if it's not in the same zone as our device (or the DeviceZone was revoked), verification fails
                if self.signed_by.get_zone() != Device.get_own_device().get_zone():
                    return False
        # by this point, we know that we're ok with accepting this model from the device that it says signed it
        # now, we just need to check whether or not it is actually signed by that model's private key
        try:
            return self.signed_by.get_key().verify(self._hashable_representation(), self.signature)
        except:
            return False
    
    def _hashable_fields(self, fields=None):
        
        # if no fields were specified, build a list of all the model's field names
        if not fields:
            fields = [field.name for field in self._meta.fields if field.name not in _unhashable_fields]
            # sort the list of fields, for consistency
            fields.sort()
        
        # certain fields should always be included
        for field in _always_hash_fields:
            if field not in fields:
                fields = [field] + fields
        
        # certain fields should never be included
        fields = [field for field in fields if field not in _unhashable_fields]
                
        return fields
    
    def _hashable_representation(self, fields=None):
        fields = self._hashable_fields(fields)
        chunks = []
        for field in fields:
            
            try:
                val = getattr(self, field)
            except ObjectDoesNotExist as e:
                # if it's a foreign key and is broken, just use the id of the related model
                val = getattr(self, field + "_id")
            
            if val:
                # convert models to just an id
                if isinstance(val, models.Model):
                    val = val.pk
                
                # convert datetimes to a str in a predictable way
                if isinstance(val, datetime.datetime):
                    val = ("%04d-%02d-%02d %d:%02d:%02d" %
                        (val.year, val.month, val.day, val.hour, val.minute, val.second))

                # encode string value as UTF-8, replacing any invalid characters so they don't blow up the hashing
                if isinstance(val, unicode):
                    val = val.encode("utf-8", "replace")

                # add this field/val pair onto the chunks to include in the hash
                chunks.append("%s=%s" % (field, val))
                
        return "&".join(chunks)

    def save(self, own_device=None, imported=False, increment_counters=True, *args, **kwargs):
        
        # we allow for the "own device" to be passed in so that a device can sign itself (before existing)
        own_device = own_device or Device.get_own_device()
        
        # this will probably never happen (since getting the device creates it), but just to be safe
        if not own_device:
            raise ValidationError("Cannot save any synced models before registering this Device.")
        
        # imported models are signed by other devices; make sure they check out
        if imported:
            if not self.signed_by_id:
                raise ValidationError("Imported models must be signed.")
            if not self.verify():
                raise ValidationError("Imported model's signature did not match.")
        else: # local models need to be signed by us
            self.counter = own_device.increment_and_get_counter()
            self.sign(device=own_device)
        
        # call the base Django Model save to write to the DB
        super(SyncedModel, self).save(*args, **kwargs)
        
        # for imported models, we want to keep track of the counter position we're at for that device
        if imported and increment_counters:
            self.signed_by.set_counter_position(self.counter)

    def get_uuid(self):
        own_device = Device.get_own_device()
        namespace = own_device.id and uuid.UUID(own_device.id) or ROOT_UUID_NAMESPACE
        return uuid.uuid5(namespace, str(self.counter)).hex

    def get_existing_instance(self):
        uuid = self.id or self.get_uuid()
        try:
            return self.__class__.objects.get(id=uuid)
        except self.__class__.DoesNotExist:
            return None

    def get_zone(self):
        # some models have a direct zone attribute; try for that
        zone = getattr(self, "zone", None)
        # otherwise, try getting the zone of the device that signed it
        if not zone and self.signed_by:
            zone = self.signed_by.get_zone()
        # otherwise, if it's signed by a trusted authority, try getting the fallback zone
        if not zone and self.signed_by and self.signed_by.get_metadata().is_trusted:
            zone = self.zone_fallback
        return zone
    get_zone.short_description = "Zone"

    def in_zone(self, zone):

kalite/templates/securesync/add_facility_user.html
{% extends 'base_distributed.html' %}
{% block addteacher_active %}{% if teacher %}active{% endif %}{% endblock addteacher_active %}
{% block addstudent_active %}{% if not teacher %}active{% endif %}{% endblock addstudent_active %}
{% block signup_active %}{% if not request.admin %}active{% endif %}{% endblock signup_active %}

{% load i18n %}

{% block title %}{% trans "Add facility user" %}{% endblock title %}

{% block content %}


<form method="post" class="basic-form">
{% csrf_token %}
<h1>{% if request.is_admin %}
		{% comment %} Translators: The sentence will be: Add a new student or teacher {% endcomment %}
		{% trans "Add a new" %}{% if teacher %}{% trans " teacher" %}{% else %}{% trans " student" %}{% endif %}
    {% else %}
        {% trans "Sign up for an account" %}
    {% endif %}
</h1>
<p><label>{% trans "Facility: " %}</label>{{ facility }} {% if not singlefacility or request.is_admin %}<a href="?facility=select">{% trans "(Select a different facility)" %}</a></p>{% endif %}
{{ form.as_p }}
{% trans "Create user" as create_user %}
<input type="submit" value="{{ create_user }}" class="submit"/>
</form>

<script>
{% if request.is_admin %}
{% trans "Add a new group" as add_new_group %}
$('#id_group').parent().find(".helptext").html('(<a href="{% url add_group %}?facility={{facility.id}}">{{add_new_group}}</a>)');
{% endif %}
{% if not request.is_admin %}
$('#id_is_teacher').parent().hide();
{% endif %}
</script>
{% endblock content %}

kalite/templates/securesync/add_group.html
{% extends 'base_distributed.html' %}

{% load i18n %}

{% block title %}{% trans "Add Group" %}{% endblock title %}

{% block content %}
<h2>{% trans "Add a new group" %}</h2>

<form method="post" class="basic-form">
    <p><label>{% trans "Facility:" %}</label>{{ facility }} <a href="?facility=select"> {% trans "(Select a different facility)" %}</a></p>

    {% csrf_token %}
    {{ form.as_p }}
    {% trans "Create group" as create_group %}
    <input type="submit" value="{{ create_group }}" class="submit"/>
</form>

<script>
$('#facility_group').change(function(){
    window.location.href = $("#facility_group option:selected").val();
});
</script>

{% endblock content %}

kalite/templates/securesync/facility_admin.html
{% extends base_template %}

{% load i18n %}

{% block title %}{% trans "Select user facility" %}{% endblock title %}

{% block headcss %}
<style>
.facility-action {
    font-size: 12px;
    margin-left: 10px;
    float: left;
    margin-bottom: 12px;
}

#facility-name {
    font-size: 14px;
    float: left;
    width: 135px;
    clear: both;
    padding-bottom: 12px;
    padding-top: 3px;
}

#add-facility-button {
    float: left;
    clear: both;
    padding-top: 30px;
}
</style>
{% endblock headcss %}

{% block content %}

<div id="facility-list-container">
    <h1>{% trans "Facilities" %}</h1>
    <div id="facility-list">
        {% if facilities %}
            {% for facility in facilities %}
            <div class="facility-title">
                <h2><div id="facility-name">{{ facility }}</div><a class="facility-action simple-button" href="{{ facility.id }}/">{% trans "Edit facility" %}</a>
                {% if not is_central %}    
                    <a class="facility-action simple-button" href="{% url add_facility_student %}?facility={{facility.id}}">{% trans "Add student" %}</a> 
                    <a class="facility-action simple-button" href="{% url add_facility_teacher %}?facility={{facility.id}}">{% trans "Add teacher" %}</a>
                    <a class="facility-action simple-button" href="{% url add_group %}?facility={{facility.id}}">{% trans "Add group" %}</a></h2>
                {% endif %}
            </div>
            {% endfor %}
            <p><a id="add-facility-button" href="new/">{% trans "Add a new Facility" %}</a><p>
        {% else %}
            <p>{% trans "You currently have no facilities. Would you like to" %} <a href="new/">{% trans "create a facility" %}</a>?</p>
        {% endif %}
    </div>
</div>

{% endblock content %}

kalite/templates/securesync/facility_edit.html
{% extends base_template %}

{% load i18n %}

{% block title %}{% trans "Facility" %}{% endblock title %}

{% block extra_head %}{{ block.super }}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUVMGp6Uks8OCczFfrWo20zHnmENyW5O0&v=3.9&sensor=false&libraries=places">
</script>
<script>
$(function() {
    $('#id_address_normalized').parent().hide();
    $('#id_zoom').parent().hide();
    $('#id_latitude').parent().hide();
    $('#id_longitude').parent().hide();
});

function displayFormLatLng(map, marker) {
    var longitude = $("#id_longitude").val();
    var latitude = $("#id_latitude").val();
    if (longitude && latitude) {
        var latLng = new google.maps.LatLng(latitude, longitude);
        map.setCenter(latLng);
        marker.setPosition(latLng);
        marker.setVisible(true);
    }
}
   
function initialize()
{
    var map = new google.maps.Map(document.getElementById('map_canvas'), {
        mapTypeId: google.maps.MapTypeId.SATELLITE,
        scrollwheel: false,
        maxZoom: 20,
        minZoom: 3,
    });
    var defaultBounds = new google.maps.LatLngBounds(
        new google.maps.LatLng(-33.8902, 151.1759),
        new google.maps.LatLng(-33.8474, 151.2631));
    map.fitBounds(defaultBounds);

    var input = document.getElementById('target');
    var searchBox = new google.maps.places.Autocomplete(input);
    
    var myLatLng = new google.maps.LatLng(-33.8902, 151.1759);

    var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        draggable: true,
        visible: false,
        clickable: true,
    });

    saveZoom(map.getZoom());

    google.maps.event.addListener(map, 'click', function(ev) {
            marker.setVisible(true);
            marker.setPosition(ev.latLng);
            saveLatLng(ev.latLng.lat(), ev.latLng.lng());
    });


    google.maps.event.addListener(searchBox, 'place_changed', function() {
        var place = searchBox.getPlace();
        var bounds = new google.maps.LatLngBounds();

        marker.setVisible(true);
        marker.setPosition(place.geometry.location);
        bounds.extend(place.geometry.location);
        saveLatLng(place.geometry.location.lat(), place.geometry.location.lng());
        getAddress(place.formatted_address);
        // if a place has a geometry, display it on the map
        if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);   
            marker.setPosition(place.geometry.viewport);
        } 
        else {
            map.setCenter(place.geometry.location);
            map.setZoom(13);
        }
    });

    $('#map_canvas').show();
    $('#id_direc_no_map').hide();
    $('#id_direc_map').show();
    google.maps.event.addListenerOnce(map, 'idle', function() {
        displayFormLatLng(map, marker);
    });

    google.maps.event.addListener(map, 'zoom_changed', function(){
        saveZoom(map.getZoom());
    });
}

google.maps.event.addDomListener(window, 'load', initialize);

function saveLatLng(lat, lon) {
    $("#id_latitude").val(lat);
    $("#id_longitude").val(lon);
}

function getAddress(ad) {
    $("#id_address_normalized").val(ad);
}

function saveZoom(zm) {
    $("#id_zoom").val(zm);
}



</script>

<style>
#map_canvas {
    display: none;
    margin-bottom: 30px;
    width: 100%;
    height: 400px
}
#search-panel {
    width: 550px;
    z-index: 5;
    background-color: #fff;
    padding: 5px;
    margin-bottom: 10px;
    border: 1px solid #999;
}       
#target {
    width: 545px;
}

#id_name {
    width: 300px;
}

#id_address {
    width: 500px;
} 

#id_latitude, #id_longitude {
    width: 150px;
}

#id_direc_map {
    display: none;
    padding-bottom: 10px;
    font-size: 14px;
}

#id_direc_no_map {
    padding-bottom: 10px;
    font-size: 14px;
}

</style>

{% endblock %}

{% block content %}
<h2>{% if form.instance.id %}{% trans "Edit a facility" %}{% else %}{% trans "Add a new Facility" %}{% endif %}</h2>
<div id="id_direc_no_map">{% trans "Please enter the following information about your facility. Please enter a detailed address, because knowing where you are in the world allows us to better plan for future deployments and partnerships." %}</div>
<div id="id_direc_map">
    {% trans "Please use this search box to locate your facility (and/or click on the map to select a spot), and then enter the additional information in the form below." %}<br/>
    {% trans "(Knowing, as closely as possible, where you are in the world allows us to better plan for future deployments and partnerships)" %}
</div>
<div id="search-panel">
    {% trans "Search for your facility's address or name to find its location on the map (enter to search)" as placeholder %}
    <input id="target" type="text" placeholder="{{placeholder}}">
</div>
<div id="map_canvas"></div>
<form id="facility_form" method="post" class="basic-form">
{% csrf_token %}
{{ form.as_p }}
{% trans "Save facility" as value %}
<input type="submit" value="{{ value }}" class="submit"/>
</form>



{% endblock content %}

kalite/templates/securesync/facility_selection.html
{% extends 'base_distributed.html' %}

{% load i18n %}

{% block title %}{% trans "Select facility" %}{% endblock title %}

{% block content %}

<div id="facility_list_container">
    <h1>{% trans "Please select a facility" %}</h1>
    <ul id="facility_list">
        {% if facilities %}
            {% for facility in facilities %}
            <li class="facility_title">
                <h2><a href="?facility={{facility.pk}}">{{ facility }}</a> {% if facilities.count > 1 %}{% if facility.is_default %} <span class=default-setter>{% trans "(this is the default)" %}</span>{% else %}<a class=default-setter href="?facility={{facility.pk}}&set_default=True"> {% trans "(set as the default facility)" %}</a>{% endif %}{% endif %}</h2>
            </li>
            {% endfor %}
        {% else %}
            {% if request.is_admin %}
                <li>{% trans "You currently have no facilities. Would you like to create a facility?" %}</li>
            {% else %}
                <li>{% trans "There are currently no facilities available, please ask an administrator or teacher to set one up." %}</li>
            {% endif %}
        {% endif %}
        {% if request.is_admin %}
            <p><a href="{% url facility_admin %}">{% trans "Administer Facilities" %}</a></p>
        {% endif %}
    </ul>
</div>

<style>
.default-setter {
    font-size: 14px;
}
</style>

{% endblock content %}

kalite/templates/securesync/login.html
{% extends 'base_distributed.html' %}

{% load i18n %}

{% block login_active %}active{% endblock login_active %}

{% block title %}{% trans "Login" %}{% endblock title %}

{% block content %}

<form method="post" class="basic-form">
    {% csrf_token %}
    
    <h2>{% trans "Login" %}</h2>

    <div style="{% if facilities.count < 2 %}display: none;{% endif %}">
        {{ form.facility.errors }}
        <p>
            {% comment %}Translators: This will be a label in a form.{% endcomment %} 
            <label for="id_facility">{% trans "Facility: " %}</label>
            {{ form.facility }}
        </p>
    </div>
    {{ form.username.errors }}
    <p>            
        {% comment %}Translators: This will be a label in a form.{% endcomment %} 
        <label for="id_username">{% trans "Username: " %}</label>
        {{ form.username }}
    </p>
    {{ form.password.errors }}
    <p>
        {% comment %}Translators: This will be a label in a form.{% endcomment %} 
        <label for="id_password">{% trans "Password: " %}</label>
        {{ form.password }}
    </p>
    {% trans "Login" as login %}
<input type="submit" value="{{ login }}" class="submit"/>
</form>

{% endblock content %}

kalite/templates/securesync/register_public_key_client.html
{% extends 'base_distributed.html' %}

{% load i18n %}

{% block register_active %}active{% endblock register_active %}

{% block title %}{% trans "Register a Device" %}{% endblock title %}

{% block headjs %}
<script>

    function reload() {
        window.location.reload();
    }

    $(function() {
        $(".refresh-link").click(reload);
    });
    
    {% if unregistered %}
    setInterval(reload, 30000);
    {% endif %}
    
</script>
{% endblock headjs %}

{% load i18n %}

{% block content %}

<h2>{% trans "Device registration" %}</h2>

{% if error_msg %}
    {% comment %}Translators: Please do not edit the variable text: %(command)s {% endcomment %}
	<p>{% blocktrans with command="<b>python manage.py update</b>"%}Sorry, there was an error during registration. Please make sure your device is fully up to date (run {{ command }} and then stop/start the server)." {% endblocktrans %}</p>
	<p>{% trans "The error message was:" %} <b>{{ error_msg }}</b></p>
{% endif %}

{% if newly_registered %}
<p>{% trans "Congratulations, this device has now been registered." %}</p>
{% endif %}

{% if already_registered %}
<p>{% trans "This device has already been registered." %}</p>
{% endif %}

{% if no_internet %}
<p>{% trans "The device needs to have internet access when first being registered. Please ensure it is connected to the internet, and then" %} <a href="." class="refresh-link">{% trans "refresh this page" %}</a>.</p>
{% endif %}

{% if unregistered %}
<p>{% trans "If you have not created an organization and zone yet, please" %} <a href="{{ central_server_host }}" target="_blank">{% trans "login to the central server and create them" %}</a> {% trans "(You will have to create an account there first)." %}</p>
<p>{% trans "If you already have an organization and a zone, please" %} <a href="{{ registration_url }}" target="_blank">{% trans "login to the central server and register this device in a zone "%}</a>{% trans "(this will open a new window)." %}</p>
<p>{% trans "Return here and" %} <a href="." class="refresh-link">{% trans "refresh this page" %}</a> {% trans "to complete the registration process." %}</p>
{% endif %}

{% endblock content %}

kalite/templates/securesync/register_public_key_server.html
{% extends 'base_central.html' %}

{% load i18n %}

{% block title %}Add facility user{% endblock title %}

{% block headjs %}
<script>
    $(function() {
        $("#id_public_key").val(decodeURIComponent(window.location.search.slice(1)));
    });
</script>
{% endblock headjs %}

{% block content %}

<form method="post" class="basic-form">
{% csrf_token %}
<h2>Register a device</h2>
{{ form.as_p }}
<input type="submit" value="Register" class="submit"/>
</form>

{% endblock content %}